#pragma once

void	vector_iterators();
void	vector_constructor();
void	vector_destructor();
void	vector_begin_end();
void	vector_rbegin_rend();
void	vector_size();
void	vector_max_size_capacity();
void	vector_empty();
void	vector_reserve();
void	vector_operator_brackets();
void	vector_at();
void	vector_front();
void	vector_back();
void	vector_assign();
void	vector_push_back();
void	vector_pop_back();
void	vector_insert();
void	vector_erase();
void	vector_swap();
void	vector_clear();
void	vector_get_allocator();
void	vector_relational_operators();
void	vector_swap();
