#pragma once
void	map_constructor();
void	map_destructor();
void	map_operator_equals();
void	map_begin_end();
void	map_rbegin_rend();
void	map_empty();
void	map_size();
void	map_max_size();
void	map_operator_brackets();
void	map_insert();
void	map_erase();
void	map_swap();
void	map_clear();
